package com.jeltechnologies.portal.tls;

import com.jeltechnologies.portal.config.AcmeProperties;
import com.jeltechnologies.portal.config.PortalProperties;
import org.shredzone.acme4j.Account;
import org.shredzone.acme4j.AccountBuilder;
import org.shredzone.acme4j.Authorization;
import org.shredzone.acme4j.Certificate;
import org.shredzone.acme4j.Order;
import org.shredzone.acme4j.Session;
import org.shredzone.acme4j.Status;
import org.shredzone.acme4j.challenge.Http01Challenge;
import org.shredzone.acme4j.util.KeyPairUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.KeyPair;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.time.Duration;
import java.time.Instant;
import java.util.Collection;
import java.util.List;

/**
 * Obtains and renews a Let's Encrypt certificate for {@code domain} via ACME (HTTP-01), and
 * atomically installs it as the SSL bundle's active cert/key. A no-op whenever no domain is
 * configured, and never allowed to crash the app — the self-signed cert generated by the
 * {@code init} container always remains a valid fallback.
 */
@Component
public class AcmeCertificateService {

    private static final Logger log = LoggerFactory.getLogger(AcmeCertificateService.class);

    private static final Path TLS_DIR = Path.of("/etc/xray/tls");
    private static final Path ACTIVE_CERT = TLS_DIR.resolve("active.crt");
    private static final Path ACTIVE_KEY = TLS_DIR.resolve("active.key");
    private static final Path ACCOUNT_KEY = TLS_DIR.resolve("acme-account.key");

    private static final Duration RENEWAL_WINDOW = Duration.ofDays(30);
    private static final Duration POLL_TIMEOUT = Duration.ofSeconds(90);

    private final PortalProperties portalProperties;
    private final AcmeProperties acmeProperties;
    private final AcmeChallengeStore challengeStore;

    public AcmeCertificateService(PortalProperties portalProperties, AcmeProperties acmeProperties,
                                   AcmeChallengeStore challengeStore) {
        this.portalProperties = portalProperties;
        this.acmeProperties = acmeProperties;
        this.challengeStore = challengeStore;
    }

    @EventListener(ApplicationReadyEvent.class)
    public void onReady() {
        Thread thread = new Thread(this::renewIfNeeded, "acme-initial-check");
        thread.setDaemon(true);
        thread.start();
    }

    @Scheduled(cron = "0 23 3 * * *")
    public void scheduledCheck() {
        renewIfNeeded();
    }

    public void renewIfNeeded() {
        if (!portalProperties.domainConfigured()) {
            return;
        }
        String domain = portalProperties.domain();

        try {
            if (activeCertCoversAndIsFresh(domain)) {
                log.debug("Active certificate already covers {} and is not due for renewal.", domain);
                return;
            }
            log.info("Requesting a Let's Encrypt certificate for {}", domain);
            issueCertificate(domain);
            log.info("Installed a new Let's Encrypt certificate for {}", domain);
        } catch (Exception e) {
            log.warn("Could not obtain/renew the Let's Encrypt certificate for {} — keeping the "
                    + "current certificate in place. Common causes: DOMAIN doesn't point at this "
                    + "server yet, or port 80 isn't reachable from the internet.", domain, e);
        }
    }

    private boolean activeCertCoversAndIsFresh(String domain) {
        if (!Files.exists(ACTIVE_CERT)) {
            return false;
        }
        try (InputStream in = Files.newInputStream(ACTIVE_CERT)) {
            CertificateFactory factory = CertificateFactory.getInstance("X.509");
            X509Certificate cert = (X509Certificate) factory.generateCertificate(in);
            boolean coversDomain = matchesDomain(cert, domain);
            boolean stillFresh = cert.getNotAfter().toInstant().isAfter(Instant.now().plus(RENEWAL_WINDOW));
            return coversDomain && stillFresh;
        } catch (IOException | CertificateException e) {
            log.warn("Could not read the current TLS certificate, will attempt to (re)issue one.", e);
            return false;
        }
    }

    private boolean matchesDomain(X509Certificate cert, String domain) throws CertificateException {
        Collection<List<?>> sanEntries = cert.getSubjectAlternativeNames();
        if (sanEntries == null) {
            return false;
        }
        for (List<?> entry : sanEntries) {
            Object value = entry.get(1);
            if (domain.equalsIgnoreCase(String.valueOf(value))) {
                return true;
            }
        }
        return false;
    }

    private void issueCertificate(String domain) throws Exception {
        Session session = new Session(acmeProperties.directoryUrl());
        KeyPair accountKeyPair = loadOrCreateKeyPair(ACCOUNT_KEY);

        Account account = new AccountBuilder()
                .agreeToTermsOfService()
                .useKeyPair(accountKeyPair)
                .create(session);

        Order order = account.newOrder().domains(List.of(domain)).create();

        for (Authorization authorization : order.getAuthorizations()) {
            completeHttp01Challenge(authorization);
        }

        order.waitUntilReady(POLL_TIMEOUT);

        KeyPair domainKeyPair = KeyPairUtils.createKeyPair(2048);
        order.execute(domainKeyPair);

        Status status = order.waitForCompletion(POLL_TIMEOUT);
        if (status != Status.VALID) {
            throw new IllegalStateException("ACME order finished with status " + status);
        }

        Certificate certificate = order.getCertificate();
        if (certificate == null) {
            throw new IllegalStateException("ACME order completed but no certificate was returned");
        }

        installCertificate(certificate, domainKeyPair);
    }

    private void completeHttp01Challenge(Authorization authorization) throws Exception {
        if (authorization.getStatus() == Status.VALID) {
            return;
        }
        Http01Challenge challenge = authorization.findChallenge(Http01Challenge.class)
                .orElseThrow(() -> new IllegalStateException(
                        "CA did not offer an HTTP-01 challenge for " + authorization.getIdentifier()));

        String token = challenge.getToken();
        challengeStore.put(token, challenge.getAuthorization());
        try {
            challenge.trigger();
            Status status = challenge.waitForCompletion(POLL_TIMEOUT);
            if (status != Status.VALID) {
                throw new IllegalStateException("HTTP-01 challenge finished with status " + status);
            }
        } finally {
            challengeStore.remove(token);
        }
    }

    private void installCertificate(Certificate certificate, KeyPair domainKeyPair) throws IOException {
        Path tmpCert = Files.createTempFile(TLS_DIR, "acme-", ".crt");
        Path tmpKey = Files.createTempFile(TLS_DIR, "acme-", ".key");
        try {
            try (FileWriter writer = new FileWriter(tmpCert.toFile())) {
                certificate.writeCertificate(writer);
            }
            try (FileWriter writer = new FileWriter(tmpKey.toFile())) {
                KeyPairUtils.writeKeyPair(domainKeyPair, writer);
            }
            // Atomic rename within the same directory so the SSL bundle's file watcher never
            // observes a half-written cert/key pair.
            Files.move(tmpCert, ACTIVE_CERT, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
            Files.move(tmpKey, ACTIVE_KEY, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
        } finally {
            Files.deleteIfExists(tmpCert);
            Files.deleteIfExists(tmpKey);
        }
    }

    private KeyPair loadOrCreateKeyPair(Path path) throws IOException {
        if (Files.exists(path)) {
            try (FileReader reader = new FileReader(path.toFile())) {
                return KeyPairUtils.readKeyPair(reader);
            }
        }
        KeyPair keyPair = KeyPairUtils.createKeyPair(2048);
        try (FileWriter writer = new FileWriter(path.toFile())) {
            KeyPairUtils.writeKeyPair(keyPair, writer);
        }
        return keyPair;
    }
}
